# name: CICD

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Source
#         uses: actions/checkout@v3

#       - name: Login to Docker Hub
#         env:
#           DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
#           DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
#         run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

#       - name: Build Docker Image
#         run: docker build -t brotin003/devops:latest .

#       - name: Publish image to Docker Hub
#         run: docker push brotin003/devops:latest   

#   deploy: 
#     needs: build
#     runs-on: ubuntu-latest
#     steps:
#       - name: Login to Docker Hub
#         env:
#           DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
#           DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
#         run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

#       - name: Pull image from Docker Hub
#         run: docker pull brotin003/devops:latest 

#       - name: Delete Old Container
#         run: docker rm -f reactContainer || true

#       - name: Run Docker Container
#         run: docker run -d -p 3000:80 --name reactContainer brotin003/devops:latest

name: CICD

on:
  push:
    branches:
      - deploy-to-ec2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t brotin003/devops .
      - name: Publish image to docker hub
        run: docker push brotin003/devops:latest   

  deploy: 
    needs: build
    runs-on: aws-ec2    
    steps:
      - name: Pull image from docker hub
        run: docker pull brotin003/devops:latest 
      - name: Delete Old Container
        run: docker rm -f reactContainer
      - name: Run docker container
        run: docker run -d -p 3000:80 --name reactContainer brotin003/devops 